version: "3"
services:

  messages:
    image: messages:latest
    ports:
      - "8081:8080"
    volumes:
      - ${PWD}/application-compose.properties:/opt/messages/application.properties
    restart: always
    depends_on:
      - messages-database

  messages-database:
    image: mysql:8
    ports: 
      - "3307:12345"
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_USER=messages-database
      - MYSQL_PASSWORD=password2
      - MYSQL_DATABASE=messages
      - MYSQL_TCP_PORT=12345
